### ISSUE TITLE
setVolume() triggers seeking

### ISSUE THREAD

**Issue by deskwizard** [pu2clr/RDA5807#1]
Hi,
I was playing around with your library, quite nice I have to say ! 

One issue I found, setVolume() actually triggers seeking.
In setVolume() you're writing reg02, and the seek bit (bit 9) is set.
I commented out the reg02 write in the setVolume() function
for the time being, I haven't seen side effects as of yet, but 
I haven't played with it much since then.

Let me know if you want me to investigate further.
There might very well be effects I haven't notice,
I'm sure there's a reason you're writing reg02.

I'm unsure if it'd be better just clearing the seek bit and still write it, or just do as I did.

Thanks!

**Comment by pu2clr** [comment]
Thanks. There is no reason to reg02 is there. It was a mistake. 
I have removed that line in setVolume(). Can you download the library and check it again?

**Comment by deskwizard** [comment]
Works wonders, and that was quick too! :)
Thanks for the library!
