### ISSUE TITLE
RDS data gibberish

### ISSUE THREAD

**Issue by deladriere** [pu2clr/RDA5807#4]
Hello 
I am trying to decode the RDS, but the data are gibberish: I can "distinguish" the station name, but most of the time, it looks randomized. (I am running the code on a SAMD21)
I first thought my board was damaged, but I can have it work well with a Raspberry (station name/ text and time) using this code 
[https://github.com/franckinux/python-rd5807m](https://github.com/franckinux/python-rd5807m)
It would really cool to update the serial monitor to show the  RDS data
thank you a lot for all your work!

**Comment by deladriere** [comment]
This is what I get
(the correct station should be CLASS.21)
  c cR21
ÆÜcRS.cR
CLAScR21
OBAScRcR
CLAScT21
CLcRS.cR
as  S.21
ÕFAS
asc cR21
asÆÜS.21
CL¿ cR21
CLAS‡ cR
CLcRcR@ 
CLcRS.21
CLcSS.21
CLcSS.21
  AScScS
CLcSp 21
CLAS  21
ascS
CLcSS.21
asc ¿ 21

**Comment by pu2clr** [comment]
I have dedicated few time to this project due to my academic activities. 
I will check and fix it  as soon as possible. 
Thanks.

**Comment by pu2clr** [comment]
Could you try it again?
