### ISSUE TITLE
Use with Wemos D1/R2 Mini (ESP8266)

### ISSUE THREAD

**Issue by MatersM** [pu2clr/RDA5807#6]
Hi Ricardo,

I've used your RDA5807 library before, and it worked like a charm!
Now I made the (stupid) mistake to use it again with en Wemos D1/R2 mini (on the Arduino IDE), and got a whole lot of errors compiling it. (happy to share all the errors if you're interested).

Any chance to get this to work with an ESP8266?

Greetz,

Martin

**Comment by pu2clr** [comment]
Fixed.

**Comment by pu2clr** [comment]
Fixed
