### ISSUE TITLE
Add new capabilities

### ISSUE THREAD

**Issue by GlebDen** [pu2clr/RDA5807#8]
Hello. Is it possible to add functions such as: getMute (); setSoftmute(); getSoftmute(); ???
something like:
RDA5807.h -> bool getMute();
RDA5807.cpp -> 
bool RDA5807::getMute()
{
    getStatus(REG0A);
    return reg02->refined.DMUTE;
}
Sorry, I'm not a programmer.
It would help a lot. Thank you.

**Comment by pu2clr** [comment]
You already have setSoftmute() in the library.  Now you have isMuted() and isSoftmuted(). They return true if muted and soft muted respectively.

**Comment by GlebDen** [comment]
Hello. Sorry to bother you but I don't see isMuted() and isSoftmuted() in source code.
