### ISSUE TITLE
Mute when volume = 0

### ISSUE THREAD

**Issue by GlebDen** [pu2clr/RDA5807#9]
Hello.
According to the RDA5807 documentation, the volume should be muted when set to 0. 
"When 0000, output mute and output impedance is very large"
Do I understand correctly?

**Comment by GlebDen** [comment]
If I call setVolume(0), then the radio continues to play as if it is a minimum volume like setVolume (1)

**Comment by pu2clr** [comment]
I think there is a problem with the text of the Documentation. 
DAC Gain Control Bits (Volume) -   0000=min; 1111=max. Volume scale is logarithmic. 
When 0000, output mute and output impedance is very large.  Should be "output mutes"? . Or "Output mute" impedance is very large when  0000?

**Comment by GlebDen** [comment]
Logically, any radio will have silence in the most minimal position.

**Comment by pu2clr** [comment]
I see... well,  in this case, it is up to the developer to decide what best applies to the project. You have the mute function by using setMute(true). If you want total silence, I think the setMute function  this is more recommended than setVolume(0). Said that, consider, via programming, testing the volume. When it is 0 (getVolume() is 0)  then setMute(true), otherwise setMute(false). I think it will do what you want. Right?

**Comment by GlebDen** [comment]
Yes, I think you're right.

**Comment by pu2clr** [comment]
I fixed some bugs today. 
The setMute function was modified. I also added the function setAudioOutputHigZ.  Both functions deal with audio output  and mute the receiver.

**Comment by GlebDen** [comment]
Thank you!
This is like an offtop, but can I suggest adding a choice of an antenna type? 
Or make reg05-> refined.lna_port_sel = 3;

**Comment by pu2clr** [comment]
I have just implemented setLnaIcSel and setLnaPortSel.  I have not tested it so far. Also I did not selected 3 by default for while due to legacy applications (I need check it before).    Can you check these functions and share the results with me? Thanks.

**Comment by GlebDen** [comment]
Hello.
I tested Setlnaicsel and Setlnaportsel.
Setlnaportsel definitely works fine.
Setlnaicsel I could not understand the changes by ear. Can this affect the RSSI level?

**Comment by pu2clr** [comment]
To be honest I have no idea what the LNA IC SEL (Setlnaicsel) really do. I cound notice here that the LNA PORT affect the RSSI. I have the same opinion about the volume. I think it is not recommended for using in  a real application. I'm not sure. It is better to control the volume with a audio amplifier module. I mean, I think we should use a fixed volume in the RDA5807 or use its high impedance setup to be processed with a good audio amplifier.  Thanks for testing.

**Comment by desenvolvedorabc** [comment]
I'm closing this issue. Please, few free to open another one if you need. Thanks.

**Comment by pu2clr** [comment]
I'm closing this issue. Please, few free to open a new one if you need. Thanks.
